### ISSUE TITLE
sitelen namako pi sitelen Lasina

### ISSUE THREAD

**Issue by KSPAtlas** [etbcor/nasin-nanpa#1]
sitelen namako (ä, ó, ũ) li lon nasin ni ala.

ona li lukin jaki.

mi wile e ni: sina pali e sitelen namako.

**Comment by etbcor** [comment]
(Note: RetSamys's commit [2ee66a6](https://github.com/RetSamys/nasin-nanpa/commit/2ee66a6286d0bc88b099befc92d2271797a8927c) does not actually refer to this issue)

> mi wile e ni: sina pali e sitelen namako.

n, sina wile e sitelen ni pi pona lukin la o alasa kepeken nasin nanpa lon poka pi nasin ante kin (pi sitelen Lasina mute).
tenpo lon la ni li suli tawa mi: nasin nanpa o suli mute ala.
