### ISSUE TITLE
zz takes up more space than a regular character

### ISSUE THREAD

**Issue by Sjlver** [ETBCOR/nasin-nanpa#11]
Note: this could well be a misunderstanding on my side: I found that `zz` produces a space that is wider than a single character. This made it hard to align some text, for example here:

![image](https://github.com/ETBCOR/nasin-nanpa/assets/72059/c44188b3-d1a3-4253-af32-350e75d8be6d)

The text for the above is:

```
<br />
kin la zz jan ante li moku e selo pakala pi (jan wawa) la<br />
zz zz jan ante li ken kama jo e wawa sama<br />
```

My expectation would be that `zz` takes the same width as a regular character. Thus if I used three `zz` on the second line, things would be aligned (one `zz` each for the `kin`, the `la`, and the `zz` in the first line)

**Comment by ETBCOR** [comment]
Ahh, I think this is happening because of the spaces after zz. The fullwidth space currently has a `space space` ligature and a `z z` ligature. I'll add a `z z space` ligature in v4 to make it more consistent with how the ligatures for glyphs work.

**Comment by ETBCOR** [comment]
Alright, this is ready in 4.0. Closing the ticket!
![image](https://github.com/ETBCOR/nasin-nanpa/assets/4682561/d848e526-b744-43ee-85c2-dcae9f791f19)
