### ISSUE TITLE
Juwan issue for youuuu <3

### ISSUE THREAD

**Issue by jnpoJuwan** [ETBCOR/nasin-nanpa#3]
* the letter a is a bit odd how it's mathematically precise
* the body on akesi is weird, in a way that I can't quite describe
* the bow in alasa reaches too far foward, it could also be rounder
* insa/sinpin/monsi are actually tiny now, heck.
* jaki seems comically out of place as it's just the pu version
* the triangle on jelo/laso/loje could be bigger
* kili should have a bit of a dent on top
* the line across kule is hard to notice on the sides
* kute could be rounder and the line in it shorter/straighter?
* lawa should be squashed on the sides, if it's a perfect circle, I can't read it well
* luka/nena/lupa are too big
  * additionally, if you want, something fun is try making lupa/nena have a bump on top to distinguish further from pona/ike
* the top circle on mama should be a bit bigger
* pona/ike are a bit too big?
* noka is too mathematically precise
* soweli can go thru some more revision
* the circle on toki is a bit too small, especially compared to tenpo. same for kokosila
* the edges of unpa are squared(?) up weirdly
* waso may have a beak way too big
* the angle on the arms for wawa could be a bit wider, with the head made smaller
* wile is still a butt
* jasima looks too big. I appreciate it fitting into a square but the telo radical is too tall
* kijetesantakalu my beloathed
* the head for soko could be bigger, extended a bit below
* lanpan has back problems
* apeja can be made to fit a square, spread those two circles atop apart
* the dots on sitelen are too small compared to other glyphs
* the head of mije is too big
* mu's ears should be above the circle instead of intersecting like linja pona (see pu mono btw)

this is everything on just the base glyphs

**Comment by ETBCOR** [comment]
(draft)
- made `akesi` a bit more rounded
- added `akesi` alt (three lines for legs)
- made palisa a bit more rounded
- made `mu`'s ear's smaller and less overlapped
- `kule`'s horizontal line got a bit wider
- `lawa` is no longer a perfect circle, it's a bit squished
-
