### ISSUE TITLE
Unexpected ligature behavior with sona+tawa(...)

### ISSUE THREAD

**Issue by snowkittykira** [ETBCOR/nasin-nanpa#4]
> sona+kama (ijo ijo ...)
> sona+tawa (ijo ijo ...)

I would expect the previous two to both render the second glyph inside of sona, however it seems like the underline takes precedence and pulls tawa out. Is this expected behavior?

![image](https://github.com/ETBCOR/nasin-nanpa/assets/71155749/74f79d48-f2e4-4926-a1ad-3dc9d1a7f5db)

**Comment by ETBCOR** [comment]
Oh that is rather interesting -- and honestly is not what I would have expected either.

Although now that I'm thinking of it I think that actually makes sense, given the current ordering of lookup tables being used. I'll experiment with adjusting that for 4.0
