### ISSUE TITLE
Improve documentation for ligatures

### ISSUE THREAD

**Issue by Sjlver** [ETBCOR/nasin-nanpa#7]
Is there a way to find out about the various ligatures that exist?

For example, I recently saw someone using `ni<^` on Discord. Until then, I had no idea that was possible.

If you can point me to a place where I can find out, I'd be happy to draft a little guide and add it to this repo.

**Comment by RetSamys** [comment]
That's true... The ligature guide in the Readme *should* have these, in addition to the image displaying the words that have variants. But the arrow variants are actually missing there, so they should get added. To make sure, I'm going through the file to check for other ligatures... No, I think everything else is accounted for in the Readme, although there might be some things you might find slightly unintuitive, like variants for cartouches. Hmmm and it seems like the Readme has more than what is in the font file, looks like & for ZWJ only describes the Hotkey, for example

**Comment by ETBCOR** [comment]
Indeed jan Ke Tami is correct -- right now the AHK scripts and the ligatures in latest released version of nasin nanpa (3.1) are out of sync as far as which characters should be used to combine glyphs. However, the I just updated the scripts and READMEs to be in sync with the ligatures I'll be using in nasin nanpa 4.

**Comment by ETBCOR** [comment]
Ah, except the directional `ni` variants -- I still need to add those to the script and readme!

Also yeah, it would be nice to have a table of all available nasin nanpa variants and how exactly to get to them in the README. I'll get to that eventually.

Thank you both for commenting, and sorry for taking so long to address this!

**Comment by Sjlver** [comment]
Thanks! The new README is fantastic!

There seems to be a backward-incompatible change: "ni:" (ni plus colon) used to render a "ni>", now it renders as downward ni followed by a colon. I think the new behavior is great. Just thought I'd mention it here for the small probability that someone faces issues during the font update to v4.0.0, and finds this :)
