### ISSUE TITLE
ibus table support

### ISSUE THREAD

**Issue by Brian3647** [ETBCOR/nasin-nanpa#8]
it'd be nice to release a ibus table versión of the autohotkey script. I don't think it'd be complicated and would help linux users who sadly don't have access to ahk. Having officially here would make it easier to have it consistently updated

If nobody wants, I can work on this tomorrow

**Comment by neroist** [comment]
https://github.com/neroist/sitelen-pona-ucsur-guide/blob/main/tokipona.txt <- ni li ike anu seme

**Comment by Brian3647** [comment]
@neroist ona li ike ala, taso ona li lon ni la ona li ken sama e lipu AHK.

**Comment by Brian3647** [comment]
kin la ni la jan mute li ken lukin e ona

**Comment by neroist** [comment]
> just to have it here to keep it up to date with the other one

ni li ken pona · o pana e wile ante

**Comment by Brian3647** [comment]
as soon as I work on it I'll open a PR - it's late today
